#!/bin/sh
### BEGIN INIT INFO
# Provides:          rocktech
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init bluetooth.
# Description:
### END INIT INFO
echo "initial bluetooth" > /dev/kmsg
. /usr/bin/bt_start.sh &

echo "initial wifi ap mode" > /dev/kmsg
create_ap wlan0 eth0 wificeshi 12345678 & 
